#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-graphviz
Version  : 0.19.2
Release  : 43
URL      : https://files.pythonhosted.org/packages/c9/0a/f196d01638f61e1ea27d90ed6874001f9c2fb7dd6281102e4555225a8ae5/graphviz-0.19.2.zip
Source0  : https://files.pythonhosted.org/packages/c9/0a/f196d01638f61e1ea27d90ed6874001f9c2fb7dd6281102e4555225a8ae5/graphviz-0.19.2.zip
Summary  : Simple Python interface for Graphviz
Group    : Development/Tools
License  : MIT
Requires: pypi-graphviz-license = %{version}-%{release}
Requires: pypi-graphviz-python = %{version}-%{release}
Requires: pypi-graphviz-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(py)
BuildRequires : pypi-pluggy
BuildRequires : pypi-pytest
BuildRequires : pypi-tox
BuildRequires : pypi-virtualenv

%description
Graphviz
========
|PyPI version| |License| |Supported Python| |Wheel| |Downloads|

%package license
Summary: license components for the pypi-graphviz package.
Group: Default

%description license
license components for the pypi-graphviz package.


%package python
Summary: python components for the pypi-graphviz package.
Group: Default
Requires: pypi-graphviz-python3 = %{version}-%{release}

%description python
python components for the pypi-graphviz package.


%package python3
Summary: python3 components for the pypi-graphviz package.
Group: Default
Requires: python3-core
Provides: pypi(graphviz)

%description python3
python3 components for the pypi-graphviz package.


%prep
%setup -q -n graphviz-0.19.2
cd %{_builddir}/graphviz-0.19.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1649476931
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-graphviz
cp %{_builddir}/graphviz-0.19.2/LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-graphviz/e5219702d881e9198520dc0c4a3a84a10737a5df
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-graphviz/e5219702d881e9198520dc0c4a3a84a10737a5df

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
