#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-graphviz
Version  : 0.19.1
Release  : 42
URL      : https://files.pythonhosted.org/packages/f6/14/aa3ec10e4ab1524ba69f4742ef9cfa01fd668d0840afe5d5e6f708a95031/graphviz-0.19.1.zip
Source0  : https://files.pythonhosted.org/packages/f6/14/aa3ec10e4ab1524ba69f4742ef9cfa01fd668d0840afe5d5e6f708a95031/graphviz-0.19.1.zip
Summary  : Simple Python interface for Graphviz
Group    : Development/Tools
License  : MIT
Requires: pypi-graphviz-license = %{version}-%{release}
Requires: pypi-graphviz-python = %{version}-%{release}
Requires: pypi-graphviz-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
Provides: python-graphviz
Provides: python-graphviz-python
Provides: python-graphviz-python3
BuildRequires : pypi(pluggy)
BuildRequires : py-python
BuildRequires : pytest
BuildRequires : tox
BuildRequires : pypi(virtualenv)

%description
Graphviz
========
|PyPI version| |License| |Supported Python| |Wheel| |Downloads|

%package license
Summary: license components for the pypi-graphviz package.
Group: Default

%description license
license components for the pypi-graphviz package.


%package python
Summary: python components for the pypi-graphviz package.
Group: Default
Requires: pypi-graphviz-python3 = %{version}-%{release}

%description python
python components for the pypi-graphviz package.


%package python3
Summary: python3 components for the pypi-graphviz package.
Group: Default
Requires: python3-core
Provides: pypi(graphviz)

%description python3
python3 components for the pypi-graphviz package.


%prep
%setup -q -n graphviz-0.19.1
cd %{_builddir}/graphviz-0.19.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1641483379
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-graphviz
cp %{_builddir}/graphviz-0.19.1/LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-graphviz/709f173a509fbb9ce7c96b1ed86b22478a41155c
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-graphviz/709f173a509fbb9ce7c96b1ed86b22478a41155c

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
